# -*- coding: utf-8 -*-
"""Extra glossary for index terms/refs not covered by titles."""
EXTRA = {
    # proper nouns keep self-describing Chinese
    "android": "Android",
    "api": "API",
    "ascii": "ASCII",
    "arithmeticerror": "ArithmeticError",
    "baseexception": "BaseException",
    "beautiful soup": "Beautiful Soup",
    "beeware toga": "BeeWare Toga",
    "boost.python": "Boost.Python",
    "cffi": "CFFI",
    "cpython": "CPython",
    "chaquopy": "Chaquopy",
    "cinder": "Cinder",
    "cython": "Cython",
    "dflr": "DFLR（深度优先从左到右）",
    "django": "Django",
    "durus": "Durus",
    "excel": "Excel",
    "fifos": "FIFO 队列",
    "hpy": "HPy",
    "haskell": "Haskell",
    "ipython": "IPython",
    "json": "JSON",
    "java": "Java",
    "jython": "Jython",
    "kivy": "Kivy",
    "latin-1": "Latin-1",
    "linux": "Linux",
    "lookuperror": "LookupError",
    "mro algorithm": "MRO 算法",
    "micropython": "MicroPython",
    "microsoft store": "Microsoft Store",
    "null character": "NULL 字符",
    "none": "None",
    "numpy": "NumPy",
    "numba": "Numba",
    "oop": "OOP（面向对象编程）",
    "oserror": "OSError",
    "pythonpath": "PYTHONPATH",
    "pythonpath directory": "PYTHONPATH 目录",
    "pycharm": "PyCharm",
    "pydev": "PyDev",
    "pypy": "PyPy",
    "pyqt": "PyQt",
    "pyscript": "PyScript",
    "pyscripter": "PyScripter",
    "pythran": "PyThran",
    "pydoc": "Pydoc",
    "pygments": "Pygments",
    "pyjamas": "Pyjamas",
    "pyodide": "Pyodide",
    "pyston": "Pyston",
    "python": "Python",
    "python virtual machine": "Python 虚拟机",
    "python versions": "Python 版本",
    "python/java bridges": "Python/Java 桥接",
    "repl": "REPL",
    "rest": "REST",
    "soap": "SOAP",
    "sqlalchemy": "SQLAlchemy",
    "sqlobject": "SQLObject",
    "sqlite": "SQLite",
    "swig": "SWIG",
    "scipy": "SciPy",
    "shed skin": "Shed Skin",
    "smartphone apps": "智能手机应用",
    "sphinx": "Sphinx",
    "spyder": "Spyder",
    "stackless": "Stackless",
    "suppress escapes": "抑制转义",
    "toga": "Toga",
    "turbogears": "TurboGears",
    "typescript": "TypeScript",
    "uis (user interfaces)": "UI（用户界面）",
    "utf-16": "UTF-16",
    "utf-8": "UTF-8",
    "unicode": "Unicode",
    "unicode code-points": "Unicode 码点",
    "unicode text": "Unicode 文本",
    "wasm (webassembly)": "Wasm（WebAssembly）",
    "webassembly/emscripten platform": "WebAssembly/Emscripten 平台",
    "xml-rpc": "XML-RPC",
    "__future__ import": "__future__ 导入",
    ".net framework for windows": "Windows 上的 .NET Framework",
    # multi-word phrases
    "as flattened tree": "作为展平树",
    "as scripting language": "作为脚本语言",
    "as signals": "作为信号",
    "assignment support": "赋值支持",
    "associative arrays": "关联数组",
    "async def": "async def",
    "backslash characters": "反斜杠字符",
    "backslash escape": "反斜杠转义",
    "backward indexing": "反向索引",
    "benchmarking automation": "基准测试自动化",
    "best uses": "最佳用途",
    "binary data": "二进制数据",
    "binary formats": "二进制格式",
    "binary mode": "二进制模式",
    "binary-mode": "二进制模式",
    "blank lines": "空行",
    "breadth-first traversal": "广度优先遍历",
    "browser mode": "浏览器模式",
    "call format": "调用格式",
    "call tracers": "调用追踪器",
    "call-chain anchors": "调用链锚点",
    "categories, catching": "按类别捕获",
    "character-code": "字符码",
    "code obfuscation": "代码混淆",
    "code points": "码点",
    "code size": "代码体积",
    "code-points": "码点",
    "combined clauses": "组合子句",
    "command line": "命令行",
    "configuration search path": "配置搜索路径",
    "conflict resolution": "冲突解决",
    "constructor convolution": "构造器的纠结",
    "control flow": "控制流",
    "control-flow": "控制流",
    "curly braces": "花括号",
    "current users": "当前用户",
    "current working directory (cwd)": "当前工作目录（CWD）",
    "custom formats": "自定义格式",
    "custom printing": "自定义打印",
    "customization by": "通过…定制",
    "data hiding": "数据隐藏",
    "databases, storage": "数据库存储",
    "decorator timers": "装饰器计时器",
    "default behavior": "默认行为",
    "default behaviors": "默认行为",
    "default encoding": "默认编码",
    "default printing": "默认打印",
    "deferring execution": "推迟执行",
    "delimiter, “changing”": "分隔符，“Changing”",
    'delimiter, "changing"': "分隔符，“Changing”",
    "direct recursion": "直接递归",
    "directory path": "目录路径",
    "directory structure": "目录结构",
    "display formats": "显示格式",
    "dotted-path": "点分路径",
    "double underscores": "双下划线",
    "empty data structures": "空数据结构",
    "enclosing-scope nonlocals": "外层作用域的 nonlocal",
    "error checks": "错误检查",
    "error handling": "错误处理",
    "error messages": "错误消息",
    "escape characters": "转义字符",
    "event handlers": "事件处理器",
    "event notification": "事件通知",
    "except clause": "except 子句",
    "except* clause": "except* 子句",
    "executables, standalone": "独立可执行文件",
    "execution environment": "执行环境",
    "extended slicing": "扩展切片",
    "fallback options": "回退选项",
    "fetching by offset": "按偏移量读取",
    "finally block": "finally 块",
    "finally clause": "finally 子句",
    "find, “changing”": "find，“Changing”",
    'find, "changing"': "find，“Changing”",
    "floating-point": "浮点",
    "folder bundles": "文件夹捆绑包",
    "folder hierarchies": "文件夹层次",
    "formatspec component": "format_spec 组件",
    "from clause": "from 子句",
    "game programming": "游戏编程",
    "garbage collection": "垃圾回收",
    "handling by assignment": "通过赋值处理",
    "has-a relationships": "“有一个”关系",
    "hello world": "Hello World",
    "help resources": "帮助资源",
    "hex escapes": "十六进制转义",
    "hex formats": "十六进制格式",
    "hierarchies, subclassing": "层次结构与子类化",
    "home directory": "主目录",
    "image processing": "图像处理",
    "incremental prototyping": "增量原型",
    "individual pythons": "多个独立 Python",
    "initialization code": "初始化代码",
    "inputs, user (see user inputs)": "用户输入（见 user inputs）",
    "insertion order": "插入顺序",
    "is-a relationships": "“是一个”关系",
    "join, “changing”": "join，“Changing”",
    'join, "changing"': "join，“Changing”",
    "learning curve": "学习曲线",
    "lexical scoping": "词法作用域",
    "like-a relationships": "“像一个”关系",
    "lines comparison": "行比较",
    "literal patterns": "字面量模式",
    "literal unpacking": "字面量解包",
    "loop avoidance": "避免循环",
    "machine code": "机器码",
    "manuals, standard": "标准手册",
    "math on user inputs": "对用户输入做数学运算",
    "multiple pythons": "多个 Python",
    "naming convention": "命名约定",
    "nesting code": "嵌套代码",
    "nesting logic": "嵌套逻辑",
    "new indexes": "新索引",
    "newline character": "换行符",
    "newline characters": "换行符",
    "non-ascii characters": "非 ASCII 字符",
    "nonempty data structures": "非空数据结构",
    "nonerror conditions": "非错误条件",
    "numeric programming": "数值编程",
    "octal formats": "八进制格式",
    "on android": "在 Android 上",
    "on linux": "在 Linux 上",
    "on windows": "在 Windows 上",
    "on ios": "在 iOS 上",
    "on macos": "在 macOS 上",
    "one-time": "一次性",
    "parallel programming": "并行编程",
    "parsing text": "解析文本",
    "per-chapter subfolders": "按章分子文件夹",
    "popularity rise": "人气上升",
    "potential problems": "潜在问题",
    "print displays": "打印显示",
    "print stream": "打印流",
    "quote characters": "引号字符",
    "restructuredtext markup language": "reStructuredText 标记语言",
    "read-only": "只读",
    "record factories": "记录工厂",
    "recursive (see recursion)": "递归（见 recursion）",
    "recursive reloaders": "递归重新加载器",
    "redirection, shells": "重定向与 shell",
    "relative magnitude": "相对大小",
    "reload variants": "reload 变体",
    "replace, “changing”": "replace，“Changing”",
    'replace, "changing"': "replace，“Changing”",
    "replacements, “changing”": "替换，“Changing”",
    'replacements, "changing"': "替换，“Changing”",
    "results generation": "结果生成",
    "returns, none": "返回 None",
    "right-side addition": "右侧加法",
    "runtime assignment": "运行时赋值",
    "scientific programming": "科学计算编程",
    "scripting language": "脚本语言",
    "search tables": "查找表",
    "secondary trees": "次级树",
    "section extraction": "章节提取",
    "selection logic": "选择逻辑",
    "server-side scripting": "服务器端脚本",
    "setup code": "启动/设置代码",
    "shell command": "shell 命令",
    "shell-command streams": "shell 命令流",
    "site-packages": "site-packages",
    "site-packages directory": "site-packages 目录",
    "special cases": "特殊情况",
    "special-case": "特殊情况",
    "special-case handling": "特殊情况处理",
    "square brackets": "方括号",
    "stack limits": "栈限制",
    "standard manuals": "标准手册",
    "standard output streams": "标准输出流",
    "standard streams": "标准流",
    "stream processors": "流处理器",
    "stream redirection": "流重定向",
    "structural pattern matching": "结构化模式匹配",
    "subprime code": "次优代码",
    "substitution targets": "替换目标",
    "substring test": "子串测试",
    "syntactic nesting": "语法嵌套",
    "systems programming": "系统编程",
    "text editors": "文本编辑器",
    "text mode": "文本模式",
    "text output": "文本输出",
    "text-mode": "文本模式",
    "textual data": "文本数据",
    "timer decorator": "计时装饰器",
    "top-level": "顶层",
    "triple-quoted block": "三引号代码块",
    "triple-quotes": "三引号",
    "typing, dynamic": "动态类型",
    "user input, error handling": "用户输入与错误处理",
    "user inputs": "用户输入",
    "user interfaces (uis)": "用户界面（UI）",
    "web servers": "Web 服务器",
    "while loop": "while 循环",
    "encoding": "编码",
    "execution": "执行",
    "folders": "文件夹",
    "dir": "dir",
    "deployment": "部署",
    "universal deployment": "通用部署",
    "nesting revisited": "再谈嵌套",
    "generating “infinite” (well, indefinite) results": "生成“无限”（实为不定长）结果",
    'generating "infinite" (well, indefinite) results': "生成“无限”（实为不定长）结果",
    "oop: the big idea": "OOP：大思想",
    "oop: the big picture": "OOP：大图景",
    "other python repls": "其他 Python REPL",
    "doing math on user inputs": "对用户输入做数学运算",
    "nesting code three levels deep": "三层嵌套代码",
    "nesting": "嵌套",
    "indexing": "索引",
    "getting help": "获取帮助",
    "a recursive reloader": "递归重新加载器",
    "automatic stream redirection": "自动流重定向",
    "manual stream redirection": "手动流重定向",
    "call format": "调用格式",
    "definition": "定义",
    "exploring shelves interactively": "交互式探索 shelf",
    "extended slicing:": "扩展切片：",
    "index": "索引",
    "intercepting slices": "拦截切片",
    "introducing python": "介绍 Python",
    "it’s portable": "它可移植",
    "it's portable": "它可移植",
    "more pydoc tips": "更多 Pydoc 技巧",
    "multiple-target assignment": "多目标赋值",
    "multiway branches: the finale": "多路分支：终章",
    "parentheses are optional": "括号可选",
    "programming by customization": "通过定制来编程",
    "providing print displays": "提供打印显示",
    "tester client": "测试客户端",
    "the async wrap-up": "异步总结",
    "the programmer’s view": "程序员视角",
    "the programmer's view": "程序员视角",
    "when import is required": "何时必须用 import",
    "bounds": "边界",
    "bounds checking": "边界检查",
    "buffering": "缓冲",
    "extending": "扩展（重复/连接）",
    "repetition": "重复",
    "repetition adds one level deep": "重复只加深一层",
    "formatting": "格式化",
    "executing": "执行",
    "step 3: run it": "第 3 步：运行它",
    "step 2: compile it (maybe)": "第 2 步：编译它（或许）",
    "magic number": "魔数",
    "ok, but what’s the downside?": "好，但缺点是什么？",
    "ok, but what's the downside?": "好，但缺点是什么？",
    "character code conversion": "字符码转换",
    "character-code conversions": "字符码转换",
    "nested": "嵌套",
    "code folders": "代码目录",
    "colons": "冒号",
    "launchers": "启动器",
    "command-line launchers": "命令行启动器",
    "commas": "逗号",
    "completion certificate": "结业证书",
    "encore: print your own completion certificate!": "安可：打印你自己的结业证书！",
    "composites": "复合",
    "multiple-choice selection": "多路选择",
    "multiple-choice selections": "多路选择",
    "handling larger actions": "处理更大型动作",
    "if clause": "if 子句",
    "filter clauses: if": "过滤子句：if",
    "constraints": "约束",
    "constructors": "构造器",
    "customizing": "定制",
    "step 5: customizing constructors, too": "第 5 步：也定制构造器",
    "control language": "控制语言",
    'is python a "scripting language"?': "Python 是“脚本语言”吗？",
    "is python a “scripting language”?": "Python 是“脚本语言”吗？",
    "conversions": "转换",
    "copies": "拷贝",
    "cyclic data": "循环数据",
    "metafunctions": "元函数",
    "runtime declarations": "运行时声明",
    "runtime execution": "运行时执行",
    "def executes at runtime": "def 在运行时执行",
    "development implications": "对开发的影响",
    "directories": "目录",
    "search-path components": "搜索路径组成部分",
    "configuring the search path": "配置搜索路径",
    "docstring standards": "文档字符串标准",
    "priorities": "优先级",
    "standards": "标准",
    "embedding": "嵌入",
    "concurrent tasks": "并发任务",
    "attribute accessors": "属性访问器",
    "boolean type": "布尔类型",
    "boolean values": "布尔值",
    "booleans": "布尔",
    "baseexception exception class": "BaseException 异常类",
    "breaking out of multiple nested loops: “go to”": "跳出多层嵌套循环：“goto”",
    'breaking out of multiple nested loops: "go to"': "跳出多层嵌套循环：“goto”",
    "csv module": "CSV 模块",
    "csv module, object storage": "CSV 模块与对象存储",
    "cwd (current working directory)": "CWD（当前工作目录）",
    "comprehensions versus type calls and generators": "推导式对比类型调用与生成器",
    "dflr (depth first, left to right)": "DFLR（深度优先、从左到右）",
    "dflr (depth first, then left to right)": "DFLR（深度优先、然后从左到右）",
    "expressions": "表达式",
    "fifo (first in, first out), queues": "FIFO（先进先出）队列",
    "fifo (first-in-first-out)": "FIFO（先进先出）",
    "ides": "IDE",
    "bom headers": "BOM 头",
    "alternatives": "替代方案",
    "are special characters": "是特殊字符",
    "basic operations": "基本操作",
    "basic dictionary operations": "字典基本操作",
    "basic list operations": "列表基本操作",
    "basic match usage": "match 基本用法",
    "advanced match usage": "match 高级用法",
    "basic usage": "基本用法",
    "attribute assignment and deletion": "属性赋值与删除",
    "attribute name qualification": "属性名限定",
    "attribute reference": "属性引用",
    "attribute-fetch algorithm": "属性获取算法",
    "augmenting methods: the bad way": "增强方法：糟糕做法",
    "augmenting methods: the good way": "增强方法：正确做法",
    "avoid mixing tabs and spaces": "避免混用 Tab 与空格",
    "avoiding missing-key errors": "避免键缺失错误",
    "adding keys, attributes, and offsets": "添加键、属性与偏移",
    "advanced f-string examples": "高级 f-string 示例",
    "advanced formatting expression examples": "高级格式化表达式示例",
    "advanced formatting method examples": "高级格式化方法示例",
    "all string methods (today)": "全部字符串方法（今日）",
    "alternative codings": "替代写法",
    "and one “object” to rule them all": "一个“object”统御万物",
    'and one "object" to rule them all': "一个“object”统御万物",
    "applying class decorators to built-in types": "把类装饰器用于内置类型",
    "applying class decorators to built- in types": "把类装饰器用于内置类型",
    "async basics": "异步基础",
    "benchmarking with python’s timeit": "用 Python 的 timeit 做基准测试",
    "benchmarking with python's timeit": "用 Python 的 timeit 做基准测试",
    "block delimiters: indentation rules": "块定界：缩进规则",
    "block rule special case": "块规则特例",
    "a “magic” proxy": "“魔法”代理",
    'a "magic" proxy': "“魔法”代理",
    "encoding": "编码",
    "execution": "执行",
    "folders": "文件夹",
    "garbage collection": "垃圾回收",
    "hierarchies, subclassing": "层次与子类化",
    "linux": "Linux",
    "macos": "macOS",
    "ios": "iOS",
    "windows": "Windows",
    # remaining brands / single words for full coverage,
    'android': 'Android 系统',
    'api': 'API（应用程序接口）',
    'ascii': 'ASCII 编码',
    'linux': 'Linux 系统',
    'macos': 'macOS 系统',
    'windows': 'Windows 系统',
    'unix': 'Unix 系统',
    'python': 'Python 语言',
    'none': 'None（空值）',
    'repl': 'REPL（交互运行环境）',
    'ides': 'IDE（集成开发环境）',
    'wsl': 'WSL（Windows 的 Linux 子系统）',
    'vscode': 'VS Code 编辑器',
    'wing': 'Wing IDE',
    'webassembly': 'WebAssembly',
    'unicode': 'Unicode 统一码',
    'utf-8': 'UTF-8 编码',
    'utf-16': 'UTF-16 编码',
    'latin-1': 'Latin-1 编码',
    'json': 'JSON 格式',
    'xml-rpc': 'XML-RPC 协议',
    'zodb': 'ZODB 数据库',
    'zope': 'Zope 框架',
    'wxpython': 'wxPython GUI 库',
    'site-packages': 'site-packages 目录',
    'pythonpath': 'PYTHONPATH 环境变量',
    'async def': 'async def（异步函数定义）',
    'async': '异步',
    'await': 'await（等待）',
    'as_completed': 'as_completed（完成即取）',
    'gather': 'gather（汇合）',
    'def': 'def（函数定义）',
    'lambda': 'lambda（匿名函数）',
    'yield': 'yield（产出）',
    'print': 'print（打印）',
    'open': 'open（打开）',
    'len': 'len（长度）',
    'dir': 'dir（目录/内省）',
    'eval': 'eval（求值）',
    'exec': 'exec（执行）',
    'filter': 'filter（过滤）',
    'reduce': 'reduce（归约）',
    'super': 'super（超类代理）',
    'classmethod': 'classmethod（类方法）',
    'staticmethod': 'staticmethod（静态方法）',
    'bytearray': 'bytearray（字节数组）',
    'str': 'str（字符串类型）',
    'struct': 'struct（结构体模块）',
    'pickle': 'pickle（序列化）',
    'shelve': 'shelve（持久字典）',
    'shelves': 'shelve 存储',
    're': 're（正则模块）',
    'try': 'try（尝试）',
    'raise': 'raise（引发）',
    'return': 'return（返回）',
    'returns': '返回值',
    'else': 'else（否则）',
    'from': 'from（导入自）',
    'import': 'import（导入）',
    'importing': '导入中',
    'reload': 'reload（重新加载）',
    'reloading': '重新加载',
    'reloads': '多次重新加载',
    'nonlocal': 'nonlocal（非局部）',
    'scope': '作用域',
    'stdout': '标准输出',
    'sys.exc_info': 'sys.exc_info',
    'sys.platform': 'sys.platform',
    'importlib.reload': 'importlib.reload',
    'try/except/else': 'try/except/else',
    'try/finally': 'try/finally',
    'if/then/else': 'if/then/else',
    'mins.py': 'mins.py 示例',
    'script1.py': 'script1.py 示例',
    'hello world': 'Hello World 示例',
    'absolute': '绝对',
    'relative': '相对',
    'access': '访问',
    'adding': '添加',
    'advanced': '高级',
    'applications': '应用',
    'assignment': '赋值',
    'automatic': '自动',
    'backslash': '反斜杠',
    'benchmarking': '基准测试',
    'benefits': '好处',
    'binary': '二进制',
    'blocks': '代码块',
    'breaks': '中断',
    'buffered': '缓冲的',
    'building': '构建',
    'callbacks': '回调',
    'catching': '捕获',
    'categories': '类别',
    'chaining': '链式',
    'changing': '更改',
    'characteristics': '特征',
    'circular': '循环的',
    'classtools': '类工具',
    'cohesion': '内聚',
    'collections': '集合容器',
    'collector': '收集器',
    'combining': '组合',
    'commands': '命令',
    'complex': '复数/复杂',
    'computing': '计算',
    'concatenation': '拼接',
    'configuring': '配置',
    'conflation': '混同',
    'consistency': '一致性',
    'construction': '构造',
    'content': '内容',
    'conversion': '转换',
    'coroutines': '协程',
    'counters': '计数器',
    'counting': '计数',
    'creation': '创建',
    'custom': '自定义',
    'customization': '定制',
    'cycles': '循环',
    'databases': '数据库',
    'debuggers': '调试器',
    'decimals': '十进制数',
    'declaring': '声明',
    'decorations': '装饰',
    'dedicated': '专用',
    'deferring': '推迟',
    'defining': '定义',
    'defs': 'def 定义',
    'delegating': '委托',
    'deleters': '删除器',
    'deleting': '删除',
    'delimiters': '分隔符',
    'designing': '设计',
    'destructors': '析构器',
    'diagonals': '对角线',
    'direct': '直接',
    'empty': '空',
    'emulation': '模拟',
    'enclosing': '外层封闭',
    'equality': '相等',
    'errors': '错误',
    'escapes': '转义',
    'executable': '可执行文件',
    'exercise': '练习',
    'exponentiation': '乘方',
    'factorials': '阶乘',
    'filename': '文件名',
    'filenames': '文件名',
    'flexibility': '灵活性',
    'format': '格式',
    'forms': '形式',
    'fractions': '分数',
    'frameworks': '框架',
    'generating': '生成',
    'handlers': '处理器',
    'hashes': '哈希',
    'hiding': '隐藏',
    'hierarchies': '层次结构',
    'hierarchy': '层次',
    'indirect': '间接',
    'inherited': '继承的',
    'initialization': '初始化',
    'initializing': '正在初始化',
    'inlining': '内联',
    'interaction': '交互',
    'intersect': '相交',
    'introspection': '内省',
    'libraries': '库',
    'links': '链接',
    'listing': '列出',
    'literals': '字面量',
    'maintenance': '维护',
    'manual': '手册/手动',
    'maps': '映射',
    'math': '数学',
    'matplotlib': 'matplotlib 绘图库',
    'matrixes': '矩阵',
    'missing': '缺失',
    'multiline': '多行',
    'multiple': '多个',
    'multiplication': '乘法',
    'multitasking': '多任务',
    'multithreading': '多线程',
    'mutability': '可变性',
    'named': '命名的',
    'noncalls': '非调用',
    'normalization': '规范化',
    'obfuscation': '混淆',
    'offsets': '偏移量',
    'order': '顺序',
    'ordering': '排序/次序',
    'ordinals': '序数',
    'output': '输出',
    'packaging': '打包',
    'pandas': 'pandas 数据分析库',
    'parameters': '参数',
    'parentheses': '圆括号',
    'parsing': '解析',
    'partitioning': '分区',
    'pathname': '路径名',
    'pathnames': '路径名',
    'paths': '路径',
    'patterns': '模式',
    'permutation': '排列',
    'pipes': '管道',
    'pointers': '指针',
    'printing': '打印',
    'privacy': '隐私',
    'private': '私有',
    'procedures': '过程',
    'profilers': '性能分析器',
    'propagating': '传播',
    'pseudoprivate': '伪私有',
    'public': '公有',
    'pyjnius': 'Pyjnius',
    'queues': '队列',
    'quotes': '引号',
    'raising': '引发',
    'random': '随机',
    'rationals': '有理数',
    'raw': '原始',
    'recursion': '递归',
    'recursive': '递归的',
    'redirecting': '重定向',
    'redundancy': '冗余',
    'removing': '移除',
    'reordering': '重排',
    'required': '必需',
    'results': '结果',
    'retaining': '保留',
    'reversing': '反转',
    'sandbox': '沙箱',
    'scripting': '脚本编写',
    'searches': '搜索',
    'searching': '搜索中',
    'selection': '选择',
    'semicolon': '分号',
    'semicolons': '分号',
    'setters': '设置器',
    'shared': '共享',
    'shipping': '发布交付',
    'size': '大小',
    'slicing': '切片',
    'sockets': '套接字',
    'sorting': '排序',
    'split': '拆分',
    'stacks': '栈',
    'standalones': '独立程序',
    'starting': '启动',
    'static': '静态',
    'storage': '存储',
    'streams': '流',
    'structure': '结构',
    'structures': '结构',
    'subclassing': '子类化',
    'subroutines': '子程序',
    'substitutions': '替换',
    'subverting': '颠覆/绕过',
    'support': '支持',
    'suspension': '挂起',
    'termination': '终止',
    'testdriver': '测试驱动器',
    'tester': '测试器',
    'toolsets': '工具集',
    'unexpected': '意外',
    'unpacking': '解包',
    'updates': '更新',
    'updating': '正在更新',
    'uses': '用途',
    'using': '使用',
    'views': '视图',
    'arithmeticerror': 'ArithmeticError 异常',
    'baseexception': 'BaseException 异常',
    'lookuperror': 'LookupError 异常',
    'oserror': 'OSError 异常',
    'beautiful soup': 'Beautiful Soup 库',
    'beeware toga': 'BeeWare Toga',
    'boost.python': 'Boost.Python',
    'cffi': 'CFFI',
    'cpython': 'CPython 实现',
    'chaquopy': 'Chaquopy',
    'cinder': 'Cinder',
    'cython': 'Cython',
    'django': 'Django Web 框架',
    'durus': 'Durus',
    'excel': 'Excel 表格',
    'hpy': 'HPy',
    'haskell': 'Haskell 语言',
    'ipython': 'IPython',
    'java': 'Java 语言',
    'jython': 'Jython',
    'kivy': 'Kivy',
    'micropython': 'MicroPython',
    'microsoft store': 'Microsoft Store',
    'numpy': 'NumPy 数值库',
    'numba': 'Numba',
    'pycharm': 'PyCharm IDE',
    'pydev': 'PyDev',
    'pypy': 'PyPy 实现',
    'pyqt': 'PyQt',
    'pyscript': 'PyScript',
    'pyscripter': 'PyScripter',
    'pythran': 'PyThran',
    'pydoc': 'Pydoc 文档工具',
    'pygments': 'Pygments',
    'pyjamas': 'Pyjamas',
    'pyodide': 'Pyodide',
    'pyston': 'Pyston',
    'rest': 'REST 风格',
    'soap': 'SOAP 协议',
    'sqlalchemy': 'SQLAlchemy ORM',
    'sqlobject': 'SQLObject',
    'sqlite': 'SQLite 数据库',
    'swig': 'SWIG',
    'scipy': 'SciPy 科学计算库',
    'shed skin': 'Shed Skin',
    'sphinx': 'Sphinx 文档',
    'spyder': 'Spyder IDE',
    'stackless': 'Stackless Python',
    'toga': 'Toga',
    'turbogears': 'TurboGears',
    'typescript': 'TypeScript',
    'zodb': 'ZODB',
    'zope': 'Zope',
    '__all__': '__all__（导出列表）',
    '__bool__': '__bool__（真值测试）',
    '__call__': '__call__（可调用）',
    '__contains__': '__contains__（成员测试）',
    '__del__': '__del__（析构）',
    '__dict__': '__dict__（属性字典）',
    '__dir__': '__dir__（属性列表）',
    '__future__': '__future__（未来特性）',
    '__get__': '__get__（描述符获取）',
    '__getattr__': '__getattr__（属性缺失钩子）',
    '__getattribute__': '__getattribute__（属性访问钩子）',
    '__getitem__': '__getitem__（索引获取）',
    '__gt__': '__gt__（大于）',
    '__iadd__': '__iadd__（就地加）',
    '__index__': '__index__（转整数索引）',
    '__iter__': '__iter__（迭代器）',
    '__lt__': '__lt__（小于）',
    '__main__': '__main__（主模块）',
    '__name__': '__name__（名字）',
    '__next__': '__next__（下一个）',
    '__radd__': '__radd__（右侧加）',
    '__repr__': '__repr__（正式表示）',
    '__self__': '__self__（绑定实例）',
    '__set__': '__set__（描述符设置）',
    '__setattr__': '__setattr__（属性设置钩子）',
    '__setitem__': '__setitem__（索引设置）',
    '__slots__': '__slots__（槽位）',
    '__str__': '__str__（字符串表示）',
}
